artsy/hokusai

README.md
bin/hokusai
hokusai/__init__.py
hokusai/config.py

Updates:
- Adds `hokusai/common.yml` and `hokusai/staging.yml`
- `hokusai build` command uses `hokusai/common.yml` - this allows for passing through environment variables as build args (see current use in Currents)
- `hokusai stack_up / stack_down` now take a context (staging or production) and implicitly look for the `{context}.yml` to create the stack, separating staging and production stacks
- `hokusai dev / test` commands now also implicitly look for `development.yml` / `test.yml` respectively
- `hokusai push` now accepts only one argument - the tag to push to the repo.  It should be called with the git SHA of the build.  The `--test-build` option should be called from CI and pushes the latest image output by the `hokusai test` command.  Otherwise it pushes the latest image output by …

Updates to config / yaml structure and push / deploy commands

---

README.md
bin/hokusai
hokusai/__init__.py

New commands:
`hokusai pull` pulls images and tags for your project from your AWS account's ECR repo for the named project
`hokusai images` lists all project images in your local docker registry
`hokusai console {CONTEXT}` launches a container and attaches a shell session in the given context
`hokusai run {CONTEXT} {COMMAND}` launches a container and runs the given command in the given context.  It exits with the status code of the command run in the container (useful for `rake` tasks, etc)
Also:
- don't update tag on deploy if it matches context
- create a tag `{CONTEXT}-utc-timestamp` on deploy
cc @cavvia

add pull, images, console and run commands

---

README.md

There's a number of formatting fixes here too. 
In general i think there's no need to discuss cli command options in depth here as using the `--help` option will be far more practical and it complicates the readme. Just an overview of the avail commands is good enough.

improve concision and scan-ability of readme. add about section.

---

README.md
bin/hokusai
hokusai/commands/__init__.py
hokusai/commands/build.py
hokusai/commands/check.py
hokusai/commands/config.py
hokusai/commands/console.py
hokusai/commands/deploy.py
hokusai/commands/development.py
hokusai/commands/init.py
hokusai/commands/promote.py
hokusai/commands/pull.py
hokusai/commands/run.py
hokusai/commands/secrets.py
hokusai/commands/stack.py
hokusai/commands/test.py
hokusai/common.py
setup.py

- Most hokusai commands now accept a `-v` / `--verbose` flag
- Adds `hokusai promote` to copy the deployment from one context to another. Use: `hokusai promote production staging` promotes production from staging
- Updates to `deploy` command to handle multiple containers in a deployment (currently affects Currents)
Coming soon! Support for multiple deployments in a given app so as to scale web / async workers independently by using Label Selectors https://kubernetes.io/docs/user-guide/labels/
cc @bhoggard @cavvia

Updates to verbosity, command outputs

---

hokusai/commands/console.py
hokusai/commands/deploy.py
hokusai/commands/promote.py
hokusai/commands/run.py

- Uses a `kubectl patch` for deployments: `hokusai deploy` / `hokusai promote` adding the "deploymentTimestamp" label to the deployment metadata, which always triggers a rollout, even if the pod image is the same
- Adds "ImagePullPolicy": "Always" to `hokusai console` and `hokusai run` commands, ensuring newest image is always run for the given tag
Update your hokusai installation with: `git pull upstream master` / `pip install --upgrade .`
cc @joeyAghion @ashkan18 @cavvia

Fix deployments and shell

---

hokusai/commands/console.py
hokusai/commands/run.py

update console and run to inject environment and imagePullPolicy with overrides as json rather than args to kubectl... this should allow working around `kubectl`'s issue parsing env vars with commas in them and allow for injecting env vars such as `FOO=123,456`
cc @joeyAghion @bhoggard @cavvia

update console and run commands

---

hokusai/commands/console.py
hokusai/commands/run.py

Run and console commands should use the pod spec, as the job spec doesn't properly return the exit code of the command in newer kubectl versions, and the console command sometimes leaves behind lingering jobs
cc @joeyAghion @cavvia

Use pod spec in run and console commands

---

README.md
bin/hokusai
hokusai/commands/__init__.py
hokusai/commands/deploy.py
hokusai/commands/development.py
hokusai/commands/history.py
hokusai/commands/setup.py
hokusai/lib/common.py
hokusai/services/deployment.py
hokusai/services/ecr.py

- Fix bug in retagging images so when redeploying so deployment update does not fail with an ECR error that the tag being deployed already exists for this image manifest
- Template Deployment strategy so that rolling updates ensure HA (always at least one container running)
- Refactor dev command to use actions `start|stop||status|logs|shell|clean` to better work with the docker-compose stack during development workflows
- Add a volume sync to the docker-compose file in `hokusai setup` - this should help local development, even if sync is slow it can be replaced with [docker-sync](http://docker-sync.io/) if a user wants to install and use that rather than docker's own volume syncing
- Add `history` command, printing out the revision history of the project's deployment(s).  I won't …

Updates to deploy, stack defaults and dev commands, add history command

---

bin/hokusai
hokusai/commands/deploy.py
hokusai/commands/promote.py
hokusai/commands/run.py
hokusai/commands/setup.py
hokusai/lib/common.py
hokusai/services/command_runner.py
test/unit/test_common.py

- Add a `--migration` flag to `deploy` and `promote` commands i.e. `hokusai deploy {SHA1} --migration bundle exec rake db:migrate` - this will launch a container at the tag specified, run the command, and only continue with the deployment / promotion if it succeeds
- Fix injecting env vars to `run` command via the `--env` flag - now verified that it will override any env vars that are present in the existing environment configmap... i.e. if `REDIS_URL=foo` is set prior, via `hokusai env set`, and the command `hokusai run bash --env REDIS_URL=bar` is run, the container will be launched with the environment `REDIS_URL=bar`
- Update `setup` to default to 2 replicas for production deployments

Add migration flag to promote and deploy - fix env injection in run command - update production default replicas

---

hokusai/services/ecr.py

Keep getting following error when trying `hokusai push`
```shell
ERROR: unknown shorthand flag: 'e' in -e
See 'docker login --help'.
```
Looks like `-e` is not an [option](https://docs.docker.com/engine/reference/commandline/login/) anymore.
Remove it :) With removing it i was able to push an image to ECR.

Remove -e from docker login command

---

bin/hokusai
docs/Command_Reference.md
hokusai/commands/__init__.py
hokusai/commands/gitdiff.py
hokusai/commands/gitlog.py

Follow up after #30 
We want to be able to see commit level diff between production..staging so we can see what's going to be deployed on next `hokusai promote`.
Added new `hokusai gitlog` and also renamed `hokusai diff` to `hokusai gitdiff` so its more descriptive.

Add gitlog, rename diff to gitdiff

---

docs/Command_Reference.md

Looks like in the doc, `gitdiff`, `gitlog`, `promote` are missing the `pipeline` command.

@anyone Fix pipeline commands in the doc

---

docs/Command_Reference.md

In the course of editing the docs to add the `--tty` flag, it seemed to me like it would be possible to eliminate some redundancy by consolidating the nearly identical `staging` and `production` sections. I'm guessing that duplication was intentional, so totally open to reverting that part. In my mind, while reading it the first time, it was almost kind of distracting in the sense of trying to figure out whether there were important functional distinctions between the `staging` and `production` cases.

add example of `--tty` flag

---

docs/Command_Reference.md
hokusai/cli/__init__.py
hokusai/cli/review_app.py
hokusai/commands/__init__.py
hokusai/commands/kubernetes.py
hokusai/commands/setup.py
hokusai/lib/common.py
hokusai/lib/namespace.py
hokusai/templates/production.yml.j2
hokusai/templates/staging.yml.j2

We want to be able to easily deploy different images of the same app on k8s.
Adding following command:
```
hokusai staging review_app create <name of the app>
```
What this command does is, it copies `staging.yaml`, adds a new `namespace` definition for this app instance and updates the `namespace` in yaml to point to newly created one and stores the result in `<app_name>.yaml`.
The idea is, we provide this `yaml` file and then we need to manually push the image with proper tag and create this deployment.

Review apps

---

docs/Getting_Started.md

It looks like the `local` keyword may have been dropped. I think this is accurate now.

delete deprecated "local"

---

docs/Getting_Started.md

In starting a Hokusai project for Node, I was initially unsure how to apply the directions. I searched in the repo for `ruby-rails` to see if it was obvious what other keywords could be substituted. It was, indeed, obvious, but it seems potentially more obvious to list the project types. The tradeoff would be that this list has to manually be kept in sync. Maybe a more robust solution would be to make the project types list dynamic and inspectable via the CLI? 
Anyway, just thought I'd open a PR in case this seemed like a good idea.

add alternate project types

---

hokusai/templates/Dockerfile-node.j2

I've experience transient issues with `yarn` failing to run due to permission issues when the Dockerfile runs on CircleCI. I feel like this might be a bit of a hack to solve the issue, but it seems to have done the trick.
[Example failied build](https://circleci.com/gh/artsy/volley/12)

fix Yarn failure in CI build

---

hokusai/cli/pipeline.py
hokusai/cli/production.py
hokusai/cli/staging.py
hokusai/commands/deployment.py
hokusai/services/deployment.py

Add the flag `--git-remote` to `hokusai [staging|production] deploy` and `hokusai pipeline promote` - if provided, push deployment tags to the specified remote.

push tags to specified git remote if provided on deploy and promote

---

CHANGELOG.md
docs/Command_Reference.md
docs/Getting_Started.md
hokusai.spec
hokusai/cli/production.py
hokusai/cli/staging.py
hokusai/commands/__init__.py
hokusai/commands/deployment.py
hokusai/commands/images.py
hokusai/services/command_runner.py
hokusai/services/deployment.py
hokusai/version.py

Notable changes:
- PyInstaller OSX build
- Push git tags to remote on deploy / promote for CI workflow
- Remove history command as it fell out of sync with multiple deployment and printed misleading information (will readdress when implementing deployment manifests in https://github.com/artsy/hokusai/issues/61)
- `registry images` command no longer prints noisy image digest
Changelog for v0.4.5:
* 1a9822a resolve this directory in hokusai.spec
* 5746219 (origin/fea-push-git-tags, fea-push-git-tags) push tags to specified git remote if provided on deploy and promote
* b6406df remove image digest from registry images output
* 2561c03 remove history command
* 3c43592 check project repo exists before updating deployment or running a command
* 5738ff4 bugfix in hokusai/services/deployment.py
* …

Version 0.4.5

---

docs/Command_Reference.md

I just had my first adventure with review apps, here are some notes to add to the docs:
- `copy_env` is actually `env_copy`
- `hokusai registry push --force --tag <name>` is probably what you'll need to do
- how to find your public urls
- interim methods for updating env vars and refreshing (issues added for adding subcommands for these: #74, #75)
- some whitespace tweaks.

Update review_app docs

---

hokusai/commands/kubernetes.py

When doing `hokusai review_app update <app name>` we noticed it uses `staging.yml` instead of the review app file yaml.
We were setting yaml file based on app name but we were using context (staging for review apps)
use `yaml_file_name` instead of context for applying deployment.

Fix using context on k8s_update and not use yaml_file_name

---

README.md

Previously this README referenced artsy/potential docs that pointed to a artsy/README link that 404'ed. After this change, this README references a now up-to-date Hokusai artsy/README playbook (see https://github.com/artsy/README/pull/80)

Update README to reference up-to-date docs

---

hokusai/commands/check.py

For the `hokusai check` command, we want to verify that required executables are available on the system. We currently call an executable's version subcommand, but the invocation varies and it's possible that an implementation may exit nonzero even if the program is available.
Instead of relying on the behavior of various `version` subcommands, simply check that the executable exists in the system `PATH`.
Addresses https://github.com/artsy/hokusai/issues/82

Update hokusai check command to find executables via which

---

hokusai/commands/check.py

During checks of production and staging Kubernetes contexts, report an error when the `kubectl` executable is unavailable.
These checks currently raise an exception when `kubectl` is unavailable:
```
ERROR: Command 'kubectl config view' returned non-zero exit status 127
```
We can instead display errors to the user:
```
staging context not found
production context not found
```

Report error when kubectl unavailable during context check

---

docs/Command_Reference.md
hokusai/cli/pipeline.py
hokusai/commands/__init__.py
hokusai/commands/gitcompare.py

Often times we want to be able to get compare link on github so we can post it on our channels let people know what commits are going to be deployed.
add `hokusai pipeline gitcompare` which by default uses github as git provider but can get a format string as input for supporting other providers (possibly)

Add `hokusai pipeline gitcompare`

---

test/__init__.py

Problem:
Before this change, boto was looking for AWS creds specified via ENV
variables or a valid ~/.aws/credentials file. This was undocumented and
complexity to setting up a clean developer / CI environment.
Solution:
Directly set the `boto3.setup_default_session` in test/__init__.py,
ensuring that any downstream boto calls would use this session.

Stub AWS session in test

---

.circleci/config.yml

This commit sets up a base Circle CI 2.0 configuration that installs
Python dependencies via Pip and runs the test suite.
It uses the docker executor with the `circleci/python:2` docker image.
Addresses https://github.com/artsy/hokusai/issues/96
Depends on https://github.com/artsy/hokusai/pull/97

Add Circle CI 2.0 configuration

---

test/unit/test_command.py

This should fix the failing test "test_command_catches_exceptions" on Linux by not checking for colorized output

Fix tests on linux

---

.circleci/config.yml

We use this release strategy for many other projects at Artsy and I think it makes sense to use here as well.
Feature development continues to be merged into the `master` branch triggering releases of `hokusai-head-${platform}-${arch}` binaries.
To release a new version, bump the version in `hokusai/VERSION` and open up a PR against the `release` branch.
Once merged, CI will build version/latest binaries and push them to S3.

Release version/latest binaries for release branch CI builds

---

.circleci/config.yml

This fixes a Circle CI workflow dependency issue in which release jobs depended on test jobs which are configured to ignore `release` branch commits. This prevented the workflow from running at all for any `release` branch commit.

Don't require `test_*` workflow jobs during release build

---

.circleci/config.yml

Rebased from `upstream/master` - drop requires as they were removed in 1829ca73bb0c7f343dd9312c1236cd64a4fdc4fa

remove requires_* steps from release_dockerhub in circleci workflow

---

.circleci/config.yml

`curl` is used to check if a docker image has already been pushed to Docker Hub with the provided version number. If so, it will halt the process.
It's worth noting that I also had to add the Docker Hub user configured for use in Circle CI builds as a collaborator with write access to the artsy/hokusai Docker Hub repository.

Install `curl` during release_dockerhub job

---

README.md

`/use/local/bin/hokusai` -> `/usr/local/bin/hokusai`

Fix README typo in binary installation snippet

---

Dockerfile

Found out that docker-compose version 1.23.0 [introduces](https://docs.docker.com/release-notes/docker-compose/) a randomly-generated hex string appended to all container names, which breaks `hokusai test` as it calls `docker wait {name of the container}` where it assumes the name of the test container to be `hokusai_{project_name}_1` - this pattern always felt shaky and indeed it's not going to work going forward.  But until we can figure out how to reliably resolve the "primary" container in test mode, pin docker-compose to version 1.22.0 so we don't break CI builds as happened [here](https://circleci.com/gh/artsy/osmosis/227).
I already ran `make image` and `make publish-dockerhub` locally so as to unblock CI builds that pull the latest Hokusai image.

lock docker-compose version to 1.22.0 in Dockerfile

---

Dockerfile

Another missing dependency in Alpine... we need the openssh client so git can push with it to remotes
Already hot-pushed new tags

add openssh client to Docker build

---

docs/Configuration_Options.md

[skip ci]
Before this change, Github was rendering a mailto link, which was unintended.

Style: Fix formatting of example repo link in docs

---

Makefile
docs/Configuration_Options.md
hokusai/cli/pipeline.py
hokusai/commands/build.py
hokusai/commands/gitcompare.py
hokusai/commands/push.py
hokusai/lib/config.py
hokusai/services/deployment.py
hokusai/services/docker.py
test/unit/test_config.py

- Fix overwriting a deployment's target if the repo is not the project's (so we can run Nginx or other sidecar containers and Hokusai won't overwrite these deployment images)
- Introduces pre-build and post-build hooks for injecting, say the commit hash like we do in Force and Positron, and doing any Docker image postprocessing (have played around with [squashing images](https://github.com/jwilder/docker-squash))
- Fixes documentation and and refactor a bit the `pipeline gitcompare` command

Fix deployment targets and introduce build hooks - update gitcompare

---

docs/Command_Reference.md
hokusai/cli/pipeline.py
hokusai/cli/production.py
hokusai/cli/registry.py
hokusai/cli/review_app.py
hokusai/cli/staging.py
hokusai/commands/configure.py
hokusai/commands/deployment.py
hokusai/commands/env.py
hokusai/commands/images.py
hokusai/commands/kubernetes.py
hokusai/commands/logs.py
hokusai/commands/push.py
hokusai/commands/test.py
hokusai/lib/common.py
hokusai/services/deployment.py
hokusai/services/ecr.py
test/unit/test_common.py

* 987a77d (HEAD -> master) add --label option to logs to filter by additional label selectors
* a10105f print newline only after verbose log line
* 1cdb7b9 add the --previous option to logs commands
* 395d57d use a unique tmp dir to download and configure kubectl
* 36316e7 refactor printing always via smart_str and add some spacing
* 538f5d5 add --timeout flag to deploy and promote and patch deployments with `progressDeadlineSeconds` when rolling out
* 8cf1ce4 add flags --reverse-sort, --limit and --filter-tags to hokusai registry images
This PR adds a default timeout of `600` seconds to all deployment rollouts by patching `deployment.spec.progressDeadlineSeconds` when rolling out new deployments.  It can be overridden by the `--timeout` flag on `hokusai [staging|production|review_app] …

Deployment timeout options, registry images output options, addition logs options and prettier printing

---

hokusai/commands/push.py
hokusai/lib/common.py
test/unit/test_common.py

Add a keyword argument `mask`, accepting a tuple of 2 regexes to `common.verbose`.  If it is supplied, it unpacks the tuple and passes items as arguments to `re.sub` and only prints the resulting output verbosely.
Also pass the `mask` kwarg through to `verbose` from `returncode`, `shout`, and `shout_concurrent` functions.
When calling `shout(ecr.get_login())` in `hokusai registry push`, mask the username and password.
Fixes https://github.com/artsy/hokusai/issues/152

mask verbose output - add a mask when shelling out to docker login

---

hokusai/lib/common.py

Follow up to https://github.com/artsy/hokusai/pull/153
Addresses the following error when promoting Metaphysics via Hokusai:
```
$ hokusai pipeline promote --git-remote upstream
Deploying 91f2817e92802c0750234604ffa43d1c160c2d98 to production...
Patching deployment metaphysics-web...
Waiting for deployment rollouts to complete...
ERROR: global name 'mask' is not defined
```

Add mask argument to shout_concurrent function

---

hokusai/cli/production.py
hokusai/cli/review_app.py
hokusai/cli/staging.py
hokusai/commands/gitdiff.py
hokusai/commands/gitlog.py
hokusai/commands/kubernetes.py
hokusai/lib/config.py
test/__init__.py
test/integration/test_kubernetes.py

Fetch from git remotes before running `hokusai [staging|production] update` which will enforce a local checkout of master up to date with _all_ remotes unless overridden.
Also perform a `git fetch` for all remotes during `hokusai pipeline git[diff|log]` commands.
Small fixes to integration tests and an error checking for verbose config when running `hokusai setup` before a configfile exists
Fixes https://github.com/artsy/hokusai/issues/41 and https://github.com/artsy/hokusai/issues/81

Introduce Git remote guards 

---

hokusai/cli/base.py
hokusai/cli/dev.py
hokusai/cli/production.py
hokusai/cli/registry.py
hokusai/cli/staging.py
hokusai/commands/__init__.py
hokusai/commands/build.py
hokusai/commands/development.py
hokusai/commands/pull.py
hokusai/commands/push.py
hokusai/commands/test.py
hokusai/services/docker.py

@dblandin the registry pull command relates to the work we did last week with Volt and @starsirius 
@ansor4 I hope the addition of the override option `--yaml-file-name` to commands like build, test and push will allow for supporting multiple build targets in a single project...

Add registry pull and override Yaml files option

---

Dockerfile

A few teams are trying out [Slack Orb](https://github.com/CircleCI-Public/slack-orb) for Slack notifications for CircleCI builds. However, it [requires bash](https://github.com/CircleCI-Public/slack-orb/tree/69d380089dfbb3e81e26d38fb982716e840521ee#bash-shell). 😞 
We can probably install it downstream in each app, but maybe we can just included in the hokusai image. Looks like `bash` is [1.25MB](https://pkgs.alpinelinux.org/package/edge/main/x86/bash) and hope it's not that much overhead.

Install bash in hokusai image

---

.circleci/config.yml
Makefile
docs/Review_Apps.md
hokusai/cli/pipeline.py
hokusai/cli/production.py
hokusai/cli/registry.py
hokusai/cli/review_app.py
hokusai/cli/staging.py
hokusai/commands/deployment.py
hokusai/commands/gitcompare.py
hokusai/commands/gitdiff.py
hokusai/commands/gitlog.py
hokusai/commands/images.py
hokusai/commands/kubernetes.py
hokusai/services/configmap.py
hokusai/services/deployment.py
hokusai/services/ecr.py
test/fixtures/ecr-images-response.json
test/integration/test_ecr.py
test/mocks/mock_ecr.py

Updates included in this PR to address a few open issues...
- Add the `--update-config` and `--filename` options to the `pipeline promote` command as in the `staging/production deploy` command (forgot to add them in the last release but we've been using them in CI 
- Alias `-u` for `--update-config`
- Add a `--environment` option to `staging/production create` so as to bootstrap a new stack with provided environment variables
- Add a `--configmap` option to `review_app env copy` so we can copy over nginx config when creating a review app and not rely on the kubed daemon to sync configmaps between namespaces that was causing PLEG issues on nodes - see https://artsyproduct.atlassian.net/browse/PLATFORM-1393
- Refactor the ECR module to expose some more useful methods to filter deployment …

Moar features and a deployment tags / ECR module refactor

---

hokusai/commands/deployment.py
hokusai/services/deployment.py

Refactor deployment behavior (see comments)
This logic should be refactored, but essentially if namespace and filename are provided, the caller is a review app, while if namespace is None it is either staging or production.  If filename is unset for staging or production it is targeting the 'canonical' app, i.e. staging.yml or production.yml while if it is set it is targeting a 'canary' app.
- For the canonical app, run deploy hooks and post-depoy steps creating deployment tags
- For a canary app, skip deploy hooks and post-deploy steps
- For review apps, run deploy hooks but skip post-deploy steps
For all deployment rollouts, if update_config or filename targets a yml file, bust the deployment cache using k8s field selectors and get deployments to watch the rollout from the yml file …

refactor deployment update behavior to account for canary and review apps

---

hokusai/commands/gitcompare.py

Small one, h/t @joeyAghion .
This command errors if you are missing a `staging` or `production` tag, but the import was missing.

@ashkan18 => [GitCompare] Import HokusaiError

---

hokusai/commands/gitcompare.py
hokusai/commands/gitlog.py
hokusai/services/configmap.py
hokusai/services/deployment.py

Addresses https://github.com/artsy/hokusai/issues/174 by serializing / deserializing ConfigMaps to JSON
@starsirius this should cast all new env vars to strings, as they are passed in to the CLI as such
Also few minor fixes relating to Git tags: fix missing HokusaiError imports in `gitcompare.py` and `gitlog.py` and fetch all git tags in `services/deployment.py`

Fix Configmap serialization and other minor issues

---

hokusai/cli/registry.py
hokusai/commands/images.py
hokusai/lib/common.py

To support CI builds that need to determine if an image with a given tag exists

add --tag-exists option to registry images command

---

docs/Review_Apps.md

`hokusai review_app env delete <name>` does not appear to be a valid command. Also, my understanding is that `hokusai review_app delete <name>` will also take care of removing env variables.

Remove unneeded command for cleanup steps

---

Pipfile
Pipfile.lock
README.md
hokusai/services/deployment.py

Further instructions for successfully installing Pythons via pyenv and packed via pipenv on MacOS - brew-installed openssl and readline as well as xcode-provided zlib packages need to be installed and linked before installing Pythons otherwise pipenv / pip installed packages can fail to compile.
Also add ipython interactive shell, ipdb line debugger and jupyter notebook server to dev dependencies

Update pyenv installation and dev dependencies

---

hokusai/commands/namespace.py

Fixes errors on `review_app setup` - note that this will render all variables in staging.yml on review app setup and they will not be interpolated in the template on further review app update  /deploys.  Unsure of a workaround as Yaml is invalid until we render the template.  Perhaps this static config is ok for review apps?
@dleve123 once this is merged if you install the `head` build of Hokusai from S3 or use the `head` Docker image tag it should be usable locally or via CI until we cut a release.

render KubernetesSpec as template on review app setup

---

hokusai/commands/development.py
hokusai/commands/kubernetes.py
hokusai/commands/namespace.py
hokusai/commands/test.py
hokusai/lib/config.py
hokusai/lib/template_selector.py
hokusai/services/configmap.py
hokusai/services/deployment.py
hokusai/services/docker.py
hokusai/services/kubernetes_spec.py
hokusai/services/yaml_spec.py
test/integration/test_review_app.py
test/unit/test_template_selector.py
test/unit/test_yaml_spec.py

- Adds TemplateSelector - For a given filename, will look for a file extension yml, yaml, yml.j2 or yaml.j2 in that order, and return the first one it finds so we can experiment with linter settings 
- Remove looking for the "legacy" docker-compose build file which was before named "common"
- Generalize KubernetesSpec to YamlSpec and render docker-compose test / development files as Jinja templates as well (this necessitates Hokusai using a project-local tmp directory)
- Utilize a project-local hokusai tmp directory for other tmpfiles

Find all Yaml j2 templates including docker-compose files

---

hokusai/services/deployment.py

We might have finally caught the git fetch error that has been causing post deploy Git tagging to fail on Circle. In this case, it happened locally from running `hokusai pipeline promote` for causality:
https://artsy.slack.com/archives/CP9P4KR35/p1592934718274700
```
WARNING: Creating Git deployment tags failed due to the error:
From github.com:artsy/causality
* branch              HEAD       -> FETCH_HEAD
! [rejected]          production -> production  (would clobber existing tag)
! [rejected]          staging    -> staging  (would clobber existing tag)
Failed all attempts at pushing Git deployment tags! Please do it manually.
```
Looks like this is what happened: Local staging/production tag exist but are out of sync with origin, which is expected. Hokusai gets to post deployment Git …

For post deployment git tagging, force git to replace local tags.

---

Makefile

Fixes the build failure `ImportError: cannot import name ensure_file_on_disk` [when creating a virtualenv](https://circleci.com/gh/artsy/hokusai/1035) by downgrading virtualenv to version 15.1.0

downgrade virtualenv to version 15.1.0 before installing pipenv

---

.circleci/config.yml
bin/hokusai
hokusai.spec

Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-2543 and https://github.com/artsy/hokusai/issues/206 - fixes the Pyinstaller build so it includes the correct homebrew-installed openssl libs
Tested on the macos Pytinstaller build.
@artsyjian once merged can you test the beta build on Linux?

fix ssl linking in pyinstaller builds

---

hokusai.spec

Only link our cafile in Pyinstaller builds on Darwin.  @artsyjian we'll have to figure out the certs that are needed for a Linux PyInstaller build if we want to use it, but given we install on Debian/Ubuntu via pip in most cases this should not be a huge blocker.

only link cafile in Darwin PyInstaller builds

---

pyproject.toml

I started to get errors installing hokusai via `pip install .` in a Docker container due to unavailable gcc tools and realized introducing the `pyproject.toml` file caused pip to use `poetry` as its build system which then installed dev dependencies.
Pip introduced support for [PEP-517 -- A build-system independent format for source trees](https://www.python.org/dev/peps/pep-0517/#source-trees) in version 10 which respects the `pyproject.toml` file and support for the `build-backend` in [version 19](https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support).  These errors only manifest while running on pip version 19 or 20 so followed the lead of [this PR](https://github.com/corrscope/corrscope/pull/229/files) to default to the legacy build backend (i.e. `setuptools`).
Here are …

Work around PEP-517 pip build system installing dev dependencies

---

.dockerignore
README.md
get-hokusai.sh
hokusai.spec
hokusai/lib/command.py
hokusai/services/configmap.py
hokusai/services/kubectl.py

Follow-up to https://github.com/artsy/hokusai/pull/212
- Fixes to JSON decoding and error handling in Python 3
- Fixes to Pyinstaller hidden import loading in Python 3
- Add a `get-hokusai.sh` script to install hokusai pyisntaller builds for latest, beta, beta3 releases easily

Further Python 3 fixes

---

hokusai/commands/development.py
hokusai/commands/test.py

Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-2672
This ensures that build settings / target specified in test.yml or dev.yml are used when building the app image in test / dev mode, so for example an intermediary build target is produced in multistage builds rather than a production or default build target specified in build.yml

use the test or development yaml template when building in test or dev environments

---

.circleci/config.yml
MANIFEST.in

- Fix to release_version_macos CircleCI job
- `pip install hokusai` failing on installing from .tar.gz (but not from using a `.whl` oddly enough) - the `VERSION` file needs to be in the MANIFEST.in file to be included 
```
Installing build dependencies ... done
Running command /Users/isacpetruzzi/Envs/test/bin/python /Users/isacpetruzzi/Envs/test/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/sg/bpbnfprn1rbb1jpkldt5d10c0000gp/T/tmplqrvqyso
Traceback (most recent call last):
File "/Users/isacpetruzzi/Envs/test/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
main()
File "/Users/isacpetruzzi/Envs/test/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main …
```

Fixes to release process / pip distribution

---

Dockerfile

Updates docker compose version to support version `3.8` templates, allowing for multi-stage builds.
I chose to upgrade conservatively to [1.25.5](https://docs.docker.com/compose/release-notes/#1255) because it includes the specific template version, the latest  version is 1.26.2 but comes with python version restrictions. 
Should resolve https://app.circleci.com/pipelines/github/artsy/horizon/796/workflows/1c1a2450-d3b8-4671-b62c-1c4e642ffa39/jobs/694

Bump docker-compose to 1.25.5

---

README.md
hokusai/lib/command.py
hokusai/lib/config.py
hokusai/services/configmap.py
hokusai/services/deployment.py
hokusai/services/yaml_spec.py

- Fixes the exception `AttributeError: 'NoneType' object has no attribute 'decode'` when catching an exception with no message or output attribute
- Fixes running hokusai in two terminal windows concurrently stomping on each other's temp directories
- Updates README.md with a 1-liner to install Hokusai via curl / bash

Fixes to exception and tempfile handling

---

hokusai/lib/command.py
hokusai/lib/common.py

Another approach following https://github.com/artsy/hokusai/pull/238
Addresses https://github.com/artsy/hokusai/issues/237
We already mask verbose output if the kwarg `mask` is provided to a subcommand via the `shout` function - this fix also applies the mask to a `CalledProcessessError`'s `cmd` and `output` attributes, should one be raised.
Also fix exception handling in the `@command` decorator and treat `HokusaiError`s separately from `CalledProcessError`s - branching for Python 2/3 compatibility.

fix: mask CalledProcessError msg and output attributes and treat HokusaiError separately from CalledProccessError on exit

---

Dockerfile

JQ is required for the new version of [Slack Orb](https://github.com/CircleCI-Public/slack-orb/wiki/FAQ). The size is [< 1MB](https://pkgs.alpinelinux.org/package/edge/main/x86/jq) so hopefully not a lot of overhead. 🙏

Install JQ in hokusai image

---

Dockerfile

Removes the docker daemon from the `artsy/hokusai` image reducing it's
size by over 30%. This will decrease the executor spin up time in
CircleCI for all repo using hokusai.

feature: Hokusai Lite

---

hokusai/commands/configure.py
hokusai/commands/images.py
hokusai/commands/logs.py
hokusai/services/ecr.py

Fixing some errors I encountered when running Hokusai via python 3 locally
When running `hokusai configure`
```
Traceback (most recent call last):
File "/home/izak/.pyenv/versions/3.7.7/lib/python3.7/site-packages/hokusai/lib/command.py", line 17, in wrapper
result = func(*args, **kwargs)
File "/home/izak/.pyenv/versions/3.7.7/lib/python3.7/site-packages/hokusai/commands/configure.py", line 43, in configure
urllib.urlretrieve("https://storage.googleapis.com/kubernetes-release/release/v%s/bin/%s/amd64/kubectl" % (kubectl_version, platform.system().lower()), os.path.join(tmpdir, 'kubectl'))
AttributeError: module 'urllib' has no attribute 'urlretrieve
```
so fixed up imports...
And when running `hokusai registry images`
```
Traceback (most recent call last):
File …
```

fix: python3 fixes

---

hokusai/commands/configure.py

The `hokusai configure` command globally configures hokusai by installing kubectl and fetching kubernetes configuration files from S3.
The command does not need to run within the context of a hokusai-configured project so I think we can safely skip this check like we currently do for `setup` and `version` commands.
Addresses #248

fix: skip project config check when configuring hokusai

---

README.md

- README instruction update: added missing python version flag when creating virtual environment. Not having this flag could cause to pick the system Python over the global Pyenv Python version, which eventually causes failure if the system version is not matching the accepted python version

doc: README added python version flag to mkvirtualenv

---

setup.py

* reverted prompt-toolkit version to 1.0.16 since later versions are not compatible with python 3.5 [https://pypi.org/project/prompt-toolkit/#history](url)
* this change may remove the possibility to install ipdb / ipython in dev mode which was added here: [https://github.com/artsy/hokusai/pull/254](url)

fix: reverted promt-toolkit version due to mismatch with python 3.5

---

hokusai/cli/registry.py
hokusai/commands/__init__.py
hokusai/commands/retag.py

For https://artsyproduct.atlassian.net/browse/PLATFORM-3372.
`hokusai staging/production deploy` (ultimately calling [service/deployment](https://github.com/artsy/hokusai/blob/master/hokusai/services/deployment.py)) does two things (among others). It updates an app's Kubernetes deployment with a new docker image. And it updates the app's docker registry tags (`staging`, `production`, etc.) so that those tags point to that image.
Some of our apps have no Kubernetes deployments. They are run by Jenkins in cron fashion. The Jenkins jobs pull `staging` tag which corresponds to the state of code-repo's `master` branch. For these apps, we don't want Kubernetes-deployment, but we do want tag-updating.
Our CI on `master` branch [pushes a new …

feat: Introduce 'hokusai registry retag' command.

---

hokusai/commands/retag.py

Fix for https://github.com/artsy/hokusai/pull/262.
Discovered that [CI build succeeded](https://app.circleci.com/pipelines/github/artsy/fulcrum/2281/workflows/259f9c19-c2fe-41df-bd0b-408d001b9bbd/jobs/3450) even though retag failed.
Update retag to raise exception.

fix: raise exception if retag fails.

---

.circleci/config.yml
hokusai/services/deployment.py
test/integration/test_kubernetes.py

Figured I'd PR this since I have been using `kubectl rollout restart` (available since v1.15) to refresh/restart deployments and the `deploymentTimestamp` metadata annotation hack necessary to trigger a deployment rollout pre- v1.15 ... this always caused problems with deployment selectors matching labels when it went out-of-sync...
Also fixed up the Kubernetes integration tests a bit so the correct configmap is created for the test deployment and pods can start, which means we can trigger a refresh, wait for it to complete before tearing down the stack.
Maybe I'll do some long-overdue refactoring now that I have some free time :D

Fea use rollout restart

---

hokusai/services/command_runner.py

Since Hokusai runs in the operator node (which includes Jenkins and other ci/cron/task executors), testing if a repository exists from this context doesn't help to tell if an image could be pulled from k8s agent node. 
The motivation for this change was this bug:
- Jenkins injecting AWS credentials that has no access to ECR target repository
- K8s node has access to ECR target repository
- hokusai production/staging run command fails due operator (jenkins) node AWS credentials having no access to ECR
So this PR:
- Remove ECR repo check on `hokusai production/staging run...`
Negative impact:
- No negative impact is expected, since: 
- testing repository doesn't help to tell if a specific tag/hash is present
- testing repository doens't help to tell if a specific k8s agent node has access …

feat: discontinue ecr repository exists test before run a kubectl command

---

hokusai/services/command_runner.py
hokusai/services/deployment.py

https://artsyproduct.atlassian.net/browse/PLATFORM-3772
This change adds _image digest_ support as a function argument to the `CommandRunner:run()` function. The calling code can now pass either a `tag` or a `digest` and the `run()` function will build a valid _image_name_.
The change modifies the _pre-deploy_ and _post-deploy_ hooks within `Deployment:update()` function where an image `tag` is being used to build an _image_name_ instead providing a `digest` to ensure that the same image is used throughout the whole deploy process.
- when a _staging_ `tag` is passed, the _image_name_ is: `123.dkr.ecr.us-east-1.amazonaws.com/some-app:staging`
- when a _sha256:111_ `digest` is passed, the _image_name_ is: `123.dkr.ecr.us-east-1.amazonaws.com/some-app@sha256:111`
This change mitigates the …

feat: add image digest support to CommandRunner:run()

---

README.md
hokusai/cli/production.py
hokusai/cli/staging.py
hokusai/commands/setup.py
hokusai/lib/branch_detection.py
hokusai/lib/default_branch.py

In order to go with the current standard we need hokusai to default to the main branch with its commands.

update: default to main instead of master

---

.circleci/config.yml
README.md

CircleCI sent an email regarding deprecation of machine images.
<details><summary>Email Screenshot</summary>
</details>
Hokusai currently uses the `circleci/classic:201808-01` in the test_integration job. I located [this blog post](https://circleci.com/blog/ubuntu-14-16-image-deprecation/) which states that in addition to 14.04 images, 16.04 images are also affected by this. Specifically the section "_Does the Ubuntu 14.04 and 16.04 image deprecation affect me?_" (includes the image tag we use):
> In addition, the following Ubuntu 16.04-based images will be removed:
>
> circleci/classic:201808-01 <-- THIS IMAGE
> ubuntu-1604:201903-01
> ubuntu-1604:202004-01
> ubuntu-1604:202007-01
> ...
Updated the config following the [suggested migration …

chore: switch test_integration image to a supported one

---

.circleci/config.yml
Dockerfile

Fix two failures in [beta release](https://app.circleci.com/pipelines/github/artsy/hokusai/635/workflows/3ace4a2e-685f-4fa8-af03-c5cc56de3816).
- `release_beta_s3_macos` failed at installing `awscli`. Some mysterious Python conflict. Switch to a binary install. Add this install to `test_macos` build so that such problem can be tested (prior to merge into `main`)
- `release_beta_dockerhub` failed at `pip install`. Resolve by undoing the `mv pyproject.toml...` command so Pip can read that file (that lists project dependencies). Add `test_docker_build` for branch builds, to catch such problem earlier. Let `release_beta_s3_linux` and `release_beta_s3_macos` require it. `release_beta_dockerhub` doesn't have to require b/c it does docker build anyway.

fix: failed beta release

---

.circleci/config.yml
README.md
get-hokusai.sh

Minor improvements:
- require all tests to pass before releasing any beta
- `brew update` is required to detect latest version of Homebrew formula
- `sudo` is required for `get-hokusai.sh` to install hokusai binary into `/usr/local/bin`
- instruct to use `get-hokusai.sh` to install beta

require all tests before beta, update get-hokusai script.

---

README.md
get-hokusai.sh

- revert `get-hokusai.sh` script. the readme already says to use `sudo` so no need to embed it in script.
- fix beta download command.

fix beta download command

---

.circleci/config.yml
Makefile

Fix bunch of errors in [v1.0.0 release build](https://app.circleci.com/pipelines/github/artsy/hokusai/663/workflows/538b1ab8-3180-4584-9965-045fce1c8935).
These changes were already pushed to `release` directly, and its [build](https://app.circleci.com/pipelines/github/artsy/hokusai/665/workflows/6f58180e-ed5b-402e-8ad0-56bba34d2429) worked (ignore `release_pip` step which failed b/c it's trying to upload v1.0.0 artifacts again).

fix: release build

---

Makefile
hokusai/cli/review_app.py
test/__init__.py
test/smoke/test_review_app.py

Resolves https://github.com/artsy/hokusai/issues/297
Force Click to keep the underscore in `review_app` command.

fix: click replacing review_app command with review-app

---

.circleci/config.yml

Ammend https://github.com/artsy/hokusai/pull/301
- use `bin.install` in homebrew formula, so that `brew install` creates `/usr/local/bin/hokusai` symlink
- let the build explicitly `git add` the formula file, so that if the file is not yet tracked by git, it will be

fix homebrew formula

---

Makefile

Fixes https://app.circleci.com/pipelines/github/artsy/hokusai/689/workflows/a4c0fa4f-75c9-4f66-9a1f-83136272e8a4/jobs/2886
`publish-version` is run by both Linux release and MacOS release. The failure was because Linux release had run, so `hokusai-$(VERSION)-Linux-x86_64` was created, which caused MacOS release to fail.
The fix is for each release check its own output file, `Linux` for Linux release, `Darwin` for MacOS release.

fix: s3 macos release publish version failure

---

.circleci/config.yml
hokusai/commands/test.py
poetry.lock

Always use the exit code from the service under test rather than additionally relying on successful exit codes for supporting services.
Example output of this not working as expected even though the service under test returned a `0` exit code:
```
hokusai-gemini-1 exited with code 0
Aborting on container exit...
[+] Running 6/6
⠿ Container hokusai-gemini-1           Stopped
⠿ Container hokusai_peril_1            Stopped
⠿ Container hokusai-gemini-redis-1     Stopped
⠿ Container hokusai_joule_1            Stopped
⠿ Container hokusai-readme-1           Stopped
⠿ Container hokusai-gemini-postgres-1  Stopped
ERROR: Tests Failed
```

feat: use --exit-code-from to ensure relevant exit code

---

Makefile

https://artsy.slack.com/archives/CA8SANW3W/p1669143642481589?thread_ts=1669137745.068279&cid=CA8SANW3W
`make publish-dockerhub` sanity checks by curl'ing against Dockerhub API to see if the new Hokusai version already exists. This curl [no longer works](https://app.circleci.com/pipelines/github/artsy/hokusai/722/workflows/e8ff870b-9f86-4b4d-bb3b-100cd009ad4f/jobs/3023) b/c Dockerhub [changed their API](https://www.docker.com/blog/docker-hub-v1-api-deprecation/). Update URL to their new API.

fix: Makefile curl on dockerhub api which has changed

---

.circleci/config.yml

https://artsy.slack.com/archives/CA8SANW3W/p1669145873115029?thread_ts=1669137745.068279&cid=CA8SANW3W
`make publish-github` uses [ghr](https://github.com/tcnksm/ghr) to pubish artifacts on Github. CircleCI `release_github` installs ghr using `go get...` which [no longer works](https://app.circleci.com/pipelines/github/artsy/hokusai/722/workflows/e8ff870b-9f86-4b4d-bb3b-100cd009ad4f/jobs/3026). Use `go install...` instead.

fix: ghr install for release github step

---

docs/Getting_Started.md

Missed this step, so thought it would helpful to update getting started docs with link to [further setup](https://github.com/artsy/README/blob/main/playbooks/deployments.md#setting-up-a-project-in-circleci).

docs(getting-started): Update with link to CircleCI setup instructions

---

poetry.lock
pyproject.toml

[PLATFORM-4759]
Remove `jupyter` from dev dependencies, because it seems not required. One benefit is that we will no longer have to spend time on [dependabot pull requests](https://github.com/artsy/hokusai/pull/312) on `jupyter` and its dependencies.
[PLATFORM-4759]: https://artsyproduct.atlassian.net/browse/PLATFORM-4759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: remove dependency on jupyter

---

Dockerfile

Hi there,
Thanks for maintaining hokusai. I've made a small improvement to the Dockerfile that I think could help optimize the image size.
Summary of Change:
* I added the `--no-cache-dir` to the `pip` command to disable the package cache.
Impact on the image size:
* Image size before repair: 539.42 MB
* Image size after repair: 529.35 MB
* Difference: 10.07 MB (1.87%)
I hope that you will find these changes useful to you. :smile:
Let me know if you have any questions or concerns.
Thanks,

Improve Dockerfile to reduce its image size

---

.circleci/config.yml
Makefile
README.md

[Builds have been failing](https://app.circleci.com/pipelines/github/artsy/hokusai/744/workflows/7d7329ba-33b1-4c38-82f0-45d816c6bbbb) at `poetry install` step. This is due to [new versions of Poetry (1.3.0+) failing to get terminal size within CI environment](https://github.com/python-poetry/poetry/issues/7184).
Let's pin Poetry to v1.2.2 (latest that does not suffer that problem) in CI, until Poetry folks have fixed the problem.
The builds are also [failing on a permissions error](https://app.circleci.com/pipelines/github/artsy/hokusai/756/workflows/bcf21e32-1460-44a2-a6f4-42fd66398144/jobs/3191) related to `--enable-framework` option for macOS python install. That option was [added in 2020 as a hotfix](https://github.com/artsy/hokusai/pull/222). I wonder if it is still relevant. Let's …

fix: CI build failures related to Poetry and Python install.

---

.circleci/config.yml

Currently, the [macOS Beta release step is failing](https://app.circleci.com/pipelines/github/artsy/hokusai/758/workflows/abe2bbfe-5e93-4232-8784-af7a624ca2bc/jobs/3202) due to authentication problem with AWS. Let's resolve it by pulling in CircleCI's `hokusai` context.

feat: let main/release builds pull in circleci hokusai context

---

.circleci/config.yml

The [previous PR](https://github.com/artsy/hokusai/pull/325) switched CI to use CircleCI context where the var for dockerhub username is configured as `DOCKERHUB_USER`. Update CircleCI config accordingly.

fix: ci reference to dockerhub username

---

README.md

Someone releasing Hokusai might want examples for writing the Pull Requests. For that person's convenience, let README link to examples.

feat: let readme have links to past release prs

---

.circleci/config.yml
scripts/create_release_tag.sh

Fix problems encountered in [Release build](https://app.circleci.com/pipelines/github/artsy/hokusai/800/workflows/33d7f7b9-d8cc-47bd-bd0b-c7eb5a021fdd).
- `release_dockerhub` failed due to build container doesn't have Bash wanted by [tag creation script](https://github.com/artsy/hokusai/blob/e2172b0a8f0a6b5f5533f9a712205ea9419f1422/scripts/create_release_tag.sh#L1). Change script to use `sh`.
- `release_pip` succeeded but after `pip install hokusai`, `hokusai version` [reports a dev version](https://github.com/artsy/hokusai/pull/340#issuecomment-1453813388). This is due to not invoking `create_release_tag.sh` in that step. Add it.

fix: release build failures

---

scripts/create_release_tag.sh

Error from [recent release build](https://app.circleci.com/pipelines/github/artsy/hokusai/807/workflows/f842916a-9437-4c93-9a8f-ce981de539d1/jobs/3432) reveals that `sh` does not support double brackets for string comparison. Switch to single bracket.
```
#!/bin/bash -eo pipefail
scripts/create_release_tag.sh
On branch: release
scripts/create_release_tag.sh: 19: [[: not found
Creating v1.0.5 tag
CircleCI received exit code 0
```

fix: create release tag script not compatible with sh

---

hokusai/cli/registry.py
hokusai/commands/__init__.py
hokusai/commands/push.py
test/unit/test_commands/test_push.py

`hokusai registry push` has a [`--force` option](https://github.com/artsy/hokusai/blob/d5f2cd3f5125c90041c5ea3a897d8e9245994200/hokusai/cli/registry.py#L19) for skipping Git status check. The option's `is_flag` is `True`, meaning if `--force` is not specified, it defaults to `False`. If `--force` is specified, it's value is `True`. So [`push`'s `force` param](https://github.com/artsy/hokusai/blob/d5f2cd3f5125c90041c5ea3a897d8e9245994200/hokusai/cli/registry.py#L23) always has value: `True` or `False`, never `None`.
The param is passed down to [`push` command](https://github.com/artsy/hokusai/blob/d5f2cd3f5125c90041c5ea3a897d8e9245994200/hokusai/commands/push.py#L11) which interprets it incorrectly - it tests `force` for `None`. This makes Git status checks always skipped.
There is a …

fix: push command not interpreting --force flag properly [#FF]

---

Dockerfile

[PLATFORM-5143]
In order to support Docker multi-stage build, specifically the [`target` field in a `docker-compose.yml`](https://docs.docker.com/compose/compose-file/compose-file-v3/#target). That doc seems to say Compose spec must be versioned 3.4 or up for the field to work. In my testing, spec with version 2 also works, as long as `docker-compose` CLI understands the field.
The current version [does not understand the field](https://app.circleci.com/pipelines/github/artsy/exchange/7430/workflows/c657cf83-a96c-4792-945e-a43ae6f9b247/jobs/12202).
[PLATFORM-5143]: https://artsyproduct.atlassian.net/browse/PLATFORM-5143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: bump Docker Compose version to v2.17.2

---

hokusai/services/docker.py

Turns out the [newer Docker Compose version](https://github.com/artsy/hokusai/pull/353) builds using [BuildKit](https://docs.docker.com/build/buildkit/) (by default). That can be disabled via Env var `DOCKER_BUILDKIT=0`. However, since BuildKit promises better performance, let's try leaving it on.
Though there's a small problem with BuildKit, where its build progress output is TTY (interactive) by default, which continuously (every fraction of a second) refreshes the screen, [overwhelming CI job's UI output](https://app.circleci.com/pipelines/github/artsy/exchange/7437/workflows/d7c0b694-37a4-433b-9f23-f5366af1fffa/jobs/12220). I don't see a benefit of this output format. Let's pass `docker-compose` the `--progress plain` option to bring back the old output format. This option differs a …

fix: docker-compose build's tty output format overwhelms CI UI output

---

poetry.lock
pyproject.toml

Solves [PHIRE-169]
[Horizon Docker image build](https://app.circleci.com/pipelines/github/artsy/horizon/2885/workflows/7859ac6e-4672-4747-9174-33e8f2c48ae2) is not able to install Hokusai v1.2.0 because of the Python v3.9.10 pin. The image is based on Alpine and we are not able to an Alpine official image that can install exactly Python v3.9.10.
This PR relaxes the pin.
[PHIRE-169]: https://artsyproduct.atlassian.net/browse/PHIRE-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: pinning 3.9.10 breaks Hokusai install in various docker images

---

hokusai/commands/development.py
hokusai/commands/test.py

Solves [PHIRE-166]
A previous PR added `COMPOSE_COMPATIBILITY=true` for Docker image build. That was to force Compose v2 to use v1's convention of naming a built image - `hokusai_<project>`, otherwise v2 uses `hokusai-<project>` instead.
It turns out that v2 applies its new naming convention (the dash) also on container names, and that some Artsy projects' CI steps rely on container names following Compose v1's convention (the underscore).
This PR applies `COMPOSE_COMPATIBILITY=true` to all docker-compose invocations, so that container names will also follow Compose V1's convention (the underscore).
[PHIRE-166]: https://artsyproduct.atlassian.net/browse/PHIRE-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: use COMPOSE_COMPATIBILITY for all docker-compose calls

---

hokusai/lib/common.py
hokusai/services/command_runner.py
test/unit/test_lib/test_common.py
test/unit/test_services/fixtures/command_runner.py
test/unit/test_services/fixtures/ecr.py
test/unit/test_services/test_command_runner.py

[PHIRE-224]
- CommandRunner#run to load project's k8s secret if it exists. It does so by inserting a `secretRef` field when generating k8s container spec. The k8s secret may or may not exist, therefore, `optional: True` is also specified. CommandRunner#run is downstream to `hokusai staging/production/review_app run ...`, so with this in place, we will be able to [migrate a project's secrets from k8s configmap to Vault](https://artsyproduct.atlassian.net/browse/PHIRE-170?focusedCommentId=58698).
Related improvements:
- Currently, CommandRunner#run performs a bunch of tasks un-related to each other, and there are no unit tests, which makes updating scary. So:
- Break down the function.
- Move the following functions to lib, since they are not closely related to CommandRunner:
- Obtaining …

feat: CommandRunner to load project's k8s secret if it exists

---

.circleci/config.yml

Running setuptools_scm in Docker image build [fails with](https://app.circleci.com/pipelines/github/artsy/hokusai/1043/workflows/576755d9-7872-4903-85ce-aa37769b6256/jobs/4453):
```
python -m setuptools_scm
/usr/local/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py:30: RuntimeWarning: 
ERROR: setuptools==58.1.0 is used in combination with setuptools_scm>=8.x
```
The build [pip installs setuptools_scm](https://github.com/artsy/hokusai/blob/b33c41c48674269b2b42ef8e8852157589341ba7/.circleci/config.yml#L104), gets v8. The error message suggests v8 requires a setuptools package version > 58.1.0, yet pip install does not bump setuptools accordingly. This suggests that this dependency requirement is present in setuptools_scm's code but not in its packaging, thus eluding …

fix: setuptools version too old for setuptools_scm

---

.circleci/config.yml
Makefile

Discovered that `python -m setuptools_scm` no longer respects [write_to](https://github.com/artsy/hokusai/blob/00af3b57fad769d57cfac77c95ad7dc5c5e8172c/pyproject.toml#L50), that is, it doesn't create `hokusai/_version.py` file anymore. We have to do `poetry build` now.

fix: setuptools_scm not writing _version.py

---

hokusai/cli/review_app.py
hokusai/commands/__init__.py
hokusai/commands/namespace.py
test/unit/test_commands/fixtures/kubectl.py
test/unit/test_commands/test_namespace.py

Solves https://github.com/artsy/hokusai/issues/126
Introduce `hokusai review_app list` command which lists review apps of the project. It does so by listing Staging cluster namespaces that are labeled with:
- app-name=<...project-name...>
- app-phase=review
`app-phase` label is already being applied to review app namespaces. This PR introduces `app-name` label.
Example usage:
```
artsy:force jxu$ /Users/jxu/.pyenv/versions/hokusai/bin/hokusai review_app list
inbox2
```

feat: hokusai review_app list command

---

scripts/update_version_file.sh

The Sed command does not work in [Mac build](https://app.circleci.com/pipelines/github/artsy/hokusai/1125/workflows/447fc776-40ca-4027-87a5-8e9bbea7fa98/jobs/4812?invite=true#step-107-183_66). CircleCI Mac instance's `sed` requires creating a backup file when editing a file in place, and a file extension must be supplied.
Change the Sed command to `sed -i.bak ...` which creates a `.bak` backup file.
It works in Linux too.

fix: sed doesn't work in circleci mac build

---

hokusai/cli/dev.py
hokusai/cli/production.py
hokusai/cli/review_app.py
hokusai/cli/staging.py
hokusai/commands/development.py
hokusai/lib/command.py

[Discovered this naming conflict during local Beta testing](https://artsy.slack.com/archives/CA8SANW3W/p1704470007870669).
```
artsy:hokusai-sandbox jxu$ hokusai version
2.0.0+fd09bac
artsy:hokusai-sandbox jxu$ hokusai staging run --tty sh
Traceback (most recent call last):
File "hokusai", line 15, in <module>
File "click/core.py", line 1130, in __call__
File "click/core.py", line 1055, in main
File "click/core.py", line 1657, in invoke
File "click/core.py", line 1657, in invoke
File "click/core.py", line 1404, in invoke
File "click/core.py", line 760, in invoke
File "hokusai/cli/staging.py", line 98, in run
TypeError: 'str' object is not callable
[4334] Failed to execute script 'hokusai' due to unhandled exception!
```

fix: naming conflict between command lib and command param

---

test/unit/test_commands/test_configure.py
test/unit/test_lib/test_common.py
test/unit/test_lib/test_config_loader.py
test/unit/test_lib/test_global_config.py

Replace this clunky construct:
```
with tempfile.TemporaryDirectory() as tmpdir
```
with pytest's [tmp_path fixture](https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html).

feat: use tmp_path fixture in pytest tests

---

.circleci/config.yml
Makefile
poetry.lock
scripts/integration_test_local.sh
test/integration/conftest.py
test/integration/test_base.py
test/integration/test_staging.py

Mainly to close out the open comments in https://github.com/artsy/hokusai/pull/400.
- Let `hokusai staging refresh` test see to `successfully rolled out` output. ([Comment addressed](https://github.com/artsy/hokusai/pull/400#discussion_r1463428499) from previous PR)
- Let CI `test_integration` step and `scripts/integration_test_local.sh` create minikube/k8s regcred for pulling image from ECR.
- Rename `make dependencies` to `make hokusai`, since Poetry installs Hokusai. ([Comment addressed](https://github.com/artsy/hokusai/pull/400#discussion_r1459270493) from previous PR)
- Rename `test_git_repo_name` fixture. ([Comment addressed](https://github.com/artsy/hokusai/pull/400#discussion_r1463383716) from previous PR)

feat: minikube k8s can pull from ECR

---

hokusai/services/kubectl.py
test/unit/test_services/test_kubectl.py

As part of troubleshooting #inc-197, we encountered this old bug, seemingly from https://github.com/artsy/hokusai/pull/379.
```
hokusai production refresh --deployment gravity-sneakers
...
ERROR: /bin/sh: -c: line 0: syntax error near unexpected token `)'
```

fix: stray paren in command to describe deployments

---

.circleci/config.yml
scripts/integration_test_local.sh

In preparation of upgrading Artsy Kubernetes clusters from v1.21.14 to [v1.22.17](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md).

feat: run integration tests against k8s 1.22.17

---

.circleci/config.yml

`ubuntu-2004:202201-02` is [no longer supported by CircleCI](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177).
Last `main` [build failure](ubuntu-2004:202201-02) [failed](https://app.circleci.com/pipelines/github/artsy/hokusai/1282/workflows/f928972a-61f6-4f87-a6a9-ba7b10974d21/jobs/5515) with:
```
This job was rejected because the image 'ubuntu-2004:202201-02' is [unavailable](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/)
```
Let's bump to [ubuntu-2204:2024.04.4](https://circleci.com/developer/machine/image/ubuntu-2204).
New image does not have Python 3.10.2. Let's have `pyenv` install Python 3.10.

fix: circleci ubuntu image deprecation

---

.circleci/config.yml

The release pipeline's:
- release_s3_macos job: [Always uploads MacOS binary to S3](https://app.circleci.com/pipelines/github/artsy/hokusai/1292/workflows/1671d5d8-b77f-4a90-8b51-5facd5415f42/jobs/5593?invite=true#step-102-932_36). If the version already exists in S3, it is overwritten. Even when there is no code changes, every PyInstaller build results in a slightly different binary, so its SHA always changes.
- release_homebrew job: [Skips updating Homebrew Formula](https://app.circleci.com/pipelines/github/artsy/hokusai/1292/workflows/1671d5d8-b77f-4a90-8b51-5facd5415f42/jobs/5593?invite=true#step-102-932_36) if version already exists. This is bad because the Formula contains SHA of MacOS binary, and this SHA should be updated every time `release_s3_macos` is run. When …

feat: overwrite homebrew formula even when version is published

---

.circleci/config.yml
Makefile
scripts/ci_macos_build_hokusai.sh

Currently, CI MacOS builds run on Intel MacOS and they output x86_64 binaries which work on Intel MacOS as well as on Apple silicon MacOS that has [Rosetta](https://support.apple.com/en-us/102527) installed.
CircleCI is [deprecating Intel MacOS](https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718). Going forward, the builds have to run on Apple silicon.
A binary built on Apple silicon does not work on Intel. When running an Apple-silicon-built binary on Intel, this error occurs:
```
artsy:hokusai-m1 jxu$ ./hokusai
-bash: ./hokusai: Bad CPU type in executable
```
In this PR, we do two things. First, we switch the builds to Apple silicon (M1), in anticipation of CircleCI's deprecation. Second, we make the builds output x86_64 binaries, so that we continue to …

Switch CI MacOS builds to M1 and continue to build x86_64 binary

---

.circleci/config.yml

https://github.com/artsy/hokusai/pull/417 changed name of MacOS S3 artifacts, [breaking](https://app.circleci.com/pipelines/github/artsy/hokusai/1318/workflows/5a6a7a55-4d70-402a-b554-8fe69b98f0e5/jobs/5705?invite=true#step-102-77_45) Homebrew release steps.
This PR updates Homebrew steps with the new names.

fix: s3 filename for homebrew formula

---

hokusai/services/deployment.py

Fix error introduced in https://github.com/artsy/hokusai/pull/426 due to lack of unit tests to `services/deployment.py`.

fix: remove extra arg to kctl.apply

---

docs/Review_Apps.md
hokusai/cli/review_app.py
hokusai/commands/__init__.py
hokusai/commands/review_app.py
test/integration/test_registry.py
test/integration/test_review_app.py
test/integration/test_staging.py

`review_app deploy` requires review app Yaml to exist. Currently, there is [automation](https://github.com/artsy/force/blob/add6c91015104bc62be61e313d125020090a21eb/scripts/update_review_app.sh#L15) that runs `review_app setup` just to create the Yaml. This automation is for updating a review app that was created prior. This no longer works because now `review_app setup` [copies configmap](https://github.com/artsy/hokusai/blob/13e7e3596b63a9925f61c8b3dc2989e26d4d79c1/hokusai/commands/review_app.py#L115), so that any configmap changes made are [overwritten](https://artsy.slack.com/archives/CA8SANW3W/p1727279164824129).
This PR adds CLI command for creating the Yaml so that those automation can switch to it.

feat: expose review app create yaml command to cli

---

hokusai/lib/common.py
hokusai/services/yaml_spec.py
test/unit/test_lib/test_common.py
test/unit/test_services/fixtures/yaml_spec.py
test/unit/test_services/test_yaml_spec.py

Small improvement over https://github.com/artsy/hokusai/pull/426.
When a [project](https://github.com/artsy/force/blob/9c892d22ce8b3735c595d03d262496ab23335f81/hokusai/staging.yml#L52) has multiple Deployments and they [reference the same configmap](https://github.com/artsy/force/blob/9c892d22ce8b3735c595d03d262496ab23335f81/hokusai/staging.yml#L144), `review_app setup` copies the configmap multiple times, example:
```
artsy:force jxu$ /Users/jxu/.pyenv/versions/hokusai/bin/hokusai review_app setup jian-test-force
namespace/jian-test-force created
Created hokusai/jian-test-force.yml
Copying force-environment ConfigMap to jian-test-force namespace...
configmap/force-environment created
Copying force-environment ConfigMap to jian-test-force namespace...
configmap/force-environment unchanged …
```

feat: review_app setup to copy a configmap or serviceaccount ref only once

---

hokusai/cli/base.py
hokusai/commands/check.py
hokusai/commands/development.py
hokusai/commands/test.py
hokusai/lib/docker_compose_helpers.py
hokusai/services/docker.py

To solve https://github.com/artsy/hokusai/issues/433
`docker compose` seems to be able to do everything `docker-compose` does.
This PR recommends that when `docker-compose` is not available, use `docker compose`. The following Hokusai commands use Docker Compose:
- `hokusai build`
- `hokusai dev`
- `hokusai test`
This PR includes the following refactors:
- Add verbosity option to `hokusai check` command.
- The responsibility of discovering `docker-compose` command is moved from `hokusai check` command to `Docker` class.
- All invocations of `docker-compose` are changed to invoke whichever command `Docker` class decides.
- The following spaghetti is moved into helpers:
```
if filename is None:
yaml_template = TemplateSelector().get(os.path.join(CWD, HOKUSAI_CONFIG_DIR, …
```

feat: fallback to "docker compose" when docker-compose not found

---

hokusai/cli/production.py
hokusai/cli/staging.py
hokusai/lib/common.py
test/integration/test_staging.py

Add interactive confirmation prompt to `hokusai production delete` and `hokusai staging delete` commands to prevent accidental deletion of Kubernetes resources. The prompt displays the project name, environment, and YAML file being used.
- Add --assume-yes/-y flag to bypass confirmation for automation
- Update integration test to use --assume-yes flag
- Confirmation message shows context: project, environment, and file path (if provided).
cc/ @brainbicycle 
**Example Invocation with Interactive Prompt**

feat: add confirmation prompt and --assume-yes flag to delete commands
