artsy/hokusai

- README.md
- bin/hokusai
- hokusai/commands/__init__.py
- hokusai/commands/check.py
- hokusai/commands/install.py
- setup.py
Other repos using Hokusai can instruct to install Hokusai and run `hokusai install --s3-bucket artsy-citadel --s3-key k8s/config`
> add hokusai install command to install and configure kubectl

- hokusai/cli/base.py
- hokusai/commands/configure.py
allow local config file as an alternative to an s3 bucket/key
> allow local config file as an alternative to an s3 bucket/key

- README.md
Updates with link to https://github.com/artsy/potential/blob/master/platform/Kubernetes.md#configuring-hokusai
> Update README with Artsy-specific config link

- docs/Command_Reference.md
Alloy asked me in slack, and I figured this would make a better answer
> Add how to do a rollback

- docs/Review_Apps.md
I hope to make "how to push subsequent changes to a review app" more clear.
> Mention how to push changes to review app in the doc

- hokusai/commands/kubernetes.py
> fix error message

- hokusai/commands/check.py
While Boto3 currently supports [multiple authentication methods][auth methods], we explicitly check that AWS credentials are configured via the environment.
This commit updates the `hokusai check` command to defer an authentication check to Boto3 via the `STS GetCallerIdentity` [API endpoint][].
[auth methods]: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#configuring-credentials
[API endpoint]: https://docs.aws.amazon.com/STS/latest/APIReference/API_GetCallerIdentity.html
> Determine if AWS credentials are valid via AWS API call

- Dockerfile
- README.md
- setup.py
- Updates to Docker build - use Alpine for slim image, used in CI
- Remove sudo from setup docs
- Add README.md as `long_description` to setup.py so it shows up in "Project description" in https://pypi.org/project/hokusai/
> Updates to Docker build and docs

- README.md
- hokusai/services/configmap.py
- Dev instructions using virtualenvs and editable pip installs
- Minor refactor in configmap.py
> Minor updates

- README.md
- docs/Configuration_Options.md
- hokusai/lib/config.py
- hokusai/services/command_runner.py
- hokusai/services/deployment.py
- test/fixtures/config.yml
- test/unit/test_config.py
Surface more config options - `git-remote` and `run-tty`.  Provide environment variable overrides.
> more config options

- .circleci/config.yml
- Makefile
Add automated version releases to PyPi, DockerHub, and GitHub.
> Release to PyPi, DockerHub, and GitHub

- docs/Configuration_Options.md
> Style: Fix hokusai typo in docs

- hokusai/services/command_runner.py
Fixes https://artsyproduct.atlassian.net/browse/AUCT-11
> Properly quote json for bash

- hokusai/services/deployment.py
Since there seems to be some confusion around this, I'll just get this implemented and merged.
cc @alloy @ashfurrow
> create and push git tags individually with --no-verify

- README.md
Updated the README with updated installation instructions, including the new preferred homebrew installation method for OSX users.
> Update README with updated installation instructions

- hokusai/commands/env.py
- hokusai/services/configmap.py
When doing 
`hokusai staging env get` the result list is not sorted which makes it hard to follow.
Sort it 📉
> Update env get to sort environment variables before print

- hokusai/services/ecr.py
refactor ECR module to provide tags, deployment_tags, current_deployment_tag methods
We can use these methods to:
a) get a sorted list of deployment tags
b) find the current deployment tag for the 'staging' tag
c) get the index of the current deployment tag (b) in the list of sorted deployment tags (a)
d) select the previous deployment tag via index - 1
e) use the `find_git_sha1_image_tag` method to resolve the deployment tag to a Git SHA1 tag
f) deploy that Git SHA1 tag (skipping creating new deployment tags)
> #WIP Implement rollback command

- docs/Getting_Started.md
Add a template example command and link to templates project.
> Add template example command

- Dockerfile
- Makefile
- Install dev dependencies within pyenv
- Run pyinstaller within pyenv
Co-authored-by: @izakp 
I think this might supersede https://github.com/artsy/hokusai/pull/193 ?
> Update Makefile dependencies/build targets

- hokusai/lib/template_selector.py
- hokusai/services/yaml_spec.py
- test/unit/test_template_selector.py
- Leave template files in temp dir if DEBUG is set
- Raise a HokusaiError if no template exists when searching for one
cc @dleve123
> Template rendering tweaks

- hokusai/services/yaml_spec.py
Strip out .j2 file extensions when rendering templates
> strip .j2 file extensions when rendering templates

- .circleci/config.yml
- Makefile
"beta" making more semantic sense when included in Orbs
> rename head builds to beta

- hokusai/services/command_runner.py
Addresses https://github.com/artsy/hokusai/issues/218
> downcase user when creating a pod name

- hokusai/cli/dev.py
- hokusai/lib/template_selector.py
because it's better, fresh-er, .., j2-er!
> prefer .j2 ;)

- Dockerfile
Follow-up to https://github.com/artsy/hokusai/pull/229
Updates build dependencies for Docker
> update build dependencies in Dockerfile

- Makefile
Hotfixing broken release build https://app.circleci.com/pipelines/github/artsy/hokusai/400/workflows/d17995cd-3353-4624-896c-ca212b35e57b
> hotfix: upgrade pip and wheel dependencies in order to fix pip errors

- hokusai/commands/check.py
Addresses https://github.com/artsy/hokusai/issues/228
> fix: check command uses TemplateSelector

- hokusai/services/command_runner.py
[PLATFORM-3388](https://artsyproduct.atlassian.net/browse/PLATFORM-3388)
Fixing hokusai failure when the username is not valid based on the regex: `[a-z0-9]([-a-z0-9]*[a-z0-9])?`
- #252
- #218
> [PLATFORM-3388] hokusai scrubs invalid characters from pod names

- .circleci/config.yml
- README.md
Favor inclusive language in the codebase per this [RFC][].
[RFC]: artsy/README#427
> feat: adopt inclusive language - main default branch

- docs/Command_Reference.md
When we wanted to rollback earlier, we ended up being a little clueless when it came to picking the image. Hopefully these changes will help. I think this is all correct but haven't done it in awhile so please look out for any errors.
> chore: Flesh out rollback docs

- .circleci/config.yml
Due to more failures in beta build.
Follows https://github.com/artsy/hokusai/pull/287
> add pyenv rehash to more macos builds

- .circleci/config.yml
Update test Kubernetes version to match our Production and Staging environments.
> feat: minor update after k8s upgrade

- hokusai/services/docker.py
Resolves https://github.com/artsy/hokusai/issues/338
> feat: use COMPOSE_COMPATIBILITY=true when building image

- CHANGELOG.md
I don't remember how we got here or where we were going, but this is the next step.
> doc: fix typo

- docs/Command_Reference.md
These instructions are Artsy-specific and [will live in Artsy's README repo](https://github.com/artsy/README/pull/528/files#diff-44da49dd742135ae99a787fd049095dc0488559cc09586ca69c12be2538b783bR97).
> feat: delete how to rollback instructions

- .circleci/config.yml
https://github.com/artsy/hokusai/pull/420 missed a single quote.
> fix: missing single quote

- .circleci/config.yml
Follows:
https://github.com/artsy/hokusai/pull/420
https://github.com/artsy/hokusai/pull/421
More artifact filename fixes.
> revise homebrew formula jobs

- README.md
adds point people to match [projects list](https://www.notion.so/artsy/Hokusai-e157f977c96949e1918e9eaa662ce8f1?v=3604e2682d024b64bde705abb2facebd&source=copy_link)
> docs: point people
